Cowell-GuestBook/Models/ARTICLE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cowell_GuestBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public ARTICLE()
        {
            this.ARTICLEREPLY = new HashSet<ARTICLEREPLY>();
        }
    
        public int ID { get; set; }
        public int FORUM_ID { get; set; }
        public string TITLE { get; set; }
        public string BODY { get; set; }
        public System.DateTime BUD_DTM { get; set; }
        public System.DateTime UPD_DTM { get; set; }
        public string AUTHOR { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual ICollection<ARTICLEREPLY> ARTICLEREPLY { get; set; }
    }
}

Cowell-GuestBook/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cowell_GuestBook.Models;

namespace Cowell_GuestBook.Controllers {
    public class ArticleController : Controller {
        private MVCTESTEntities db = new MVCTESTEntities();

        public ActionResult Index(int? ForumID) {
            IQueryable<ARTICLE> objs;
            if (ForumID == null) {
                // Get: /Article
                objs = db.ARTICLE.Include(a => a.Forum);
            } else {
                // Get: /Article?forumID=12
                objs = db.ARTICLE.Where(x => x.FORUM_ID == ForumID).OrderBy(x => x.BUD_DTM);
                ViewData["ForumDetailModel"] = db.Forum.Find(ForumID);
            }
            return View(objs.ToList());
        }

        // GET: Article/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLE aRTICLE = db.ARTICLE.Find(id);
            if (aRTICLE == null) {
                return HttpNotFound();
            }

            return View(aRTICLE);
        }

        // GET: Article/Create
        public ActionResult Create(int? ForumID) {
            //新建文章已經限定一定要從討論區才能新建
            if (ForumID == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //驗證討論區是否存在
            Forum f = db.Forum.Find(ForumID);
            if (f == null) {
                return HttpNotFound();
            }
            ViewData["ForumID"] = ForumID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection frm) {

            ARTICLE obj = new ARTICLE();
            obj.BUD_DTM = DateTime.Now;
            obj.UPD_DTM = DateTime.Now;
            if (TryUpdateModel<ARTICLE>(obj, "", frm.AllKeys, new string[] { })) {
                db.ARTICLE.Add(obj);
                db.SaveChanges();
                return RedirectToAction("index", "article", new { forumID=obj.FORUM_ID});
            }
            return View(obj);
        }

        // GET: Article/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLE aRTICLE = db.ARTICLE.Find(id);
            if (aRTICLE == null) {
                return HttpNotFound();
            }
            return View(aRTICLE);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,FormCollection frm) {
            var obj = db.ARTICLE.Find(id);
            obj.UPD_DTM = DateTime.Now;
            if (TryUpdateModel<ARTICLE>(obj, "", frm.AllKeys, new string[] { "BUD_DTM" })) {
                db.SaveChanges();
                return RedirectToAction("index", "article", new { ForumID = obj.FORUM_ID });
            }
            return View(obj);
        }

        // GET: Article/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLE aRTICLE = db.ARTICLE.Find(id);
            if (aRTICLE == null) {
                return HttpNotFound();
            }
            return View(aRTICLE);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            ARTICLE obj = db.ARTICLE.Find(id);
            db.ARTICLE.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("index", "article", new { forumID = obj.FORUM_ID });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cowell-GuestBook/Controllers/replyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cowell_GuestBook.Models;

namespace Cowell_GuestBook.Controllers {
    public class replyController : Controller {
        private MVCTESTEntities db = new MVCTESTEntities();

        // GET: reply
        public ActionResult Index(int? ArticleID) {
            IQueryable<ARTICLEREPLY> objs;
            if (ArticleID == null) {
                objs = db.ARTICLEREPLY.Include(a => a.ARTICLE);
            } else {
                objs = db.ARTICLEREPLY.Where(x => x.ARTICLE_ID == ArticleID).OrderBy(x => x.BUD_DTM);
                ViewData["ArticleID"] = ArticleID;
            }
            return View(objs.ToList());
        }

        // GET: reply/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLEREPLY aRTICLEREPLY = db.ARTICLEREPLY.Find(id);
            if (aRTICLEREPLY == null) {
                return HttpNotFound();
            }
            return View(aRTICLEREPLY);
        }

        // GET: reply/Create
        public ActionResult Create(int? articleID) {
            if (articleID == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewData["articleID"] = articleID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection frm) {
            ARTICLEREPLY obj = new ARTICLEREPLY();
            obj.BUD_DTM = DateTime.Now;
            if (TryUpdateModel<ARTICLEREPLY>(obj, "", frm.AllKeys, new string[] {"" })) {
                db.ARTICLEREPLY.Add(obj);
                db.SaveChanges();
                return RedirectToAction("details", "article", new { ID = obj.ARTICLE_ID });
            }
            return View(obj);
        }

        // GET: reply/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLEREPLY aRTICLEREPLY = db.ARTICLEREPLY.Find(id);
            if (aRTICLEREPLY == null) {
                return HttpNotFound();
            }
            
            return View(aRTICLEREPLY);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,FormCollection frm) {
            var obj = db.ARTICLEREPLY.Find(id);
            if (TryUpdateModel<ARTICLEREPLY>(obj, "", frm.AllKeys, new string[] { })) {
                db.SaveChanges();
                return RedirectToAction("details", "article", new { ID = obj.ARTICLE_ID });
            }
                return View(obj);
        }

        // GET: reply/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ARTICLEREPLY aRTICLEREPLY = db.ARTICLEREPLY.Find(id);
            if (aRTICLEREPLY == null) {
                return HttpNotFound();
            }
            return View(aRTICLEREPLY);
        }

        // POST: reply/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            ARTICLEREPLY aRTICLEREPLY = db.ARTICLEREPLY.Find(id);
            db.ARTICLEREPLY.Remove(aRTICLEREPLY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cowell-GuestBook/Views/Article/Create.cshtml
@model Cowell_GuestBook.Models.ARTICLE

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ARTICLE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="hidden" id="Forum_ID" name="Forum_ID" value="@ViewData["ForumID"]" />

        <div class="form-group">
            @Html.LabelFor(model => model.TITLE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TITLE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TITLE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AUTHOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AUTHOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AUTHOR, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BODY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.BODY, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.BODY, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cowell-GuestBook/Views/Article/Delete.cshtml
@model Cowell_GuestBook.Models.ARTICLE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ARTICLE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TITLE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TITLE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BODY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BODY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BUD_DTM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BUD_DTM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UPD_DTM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UPD_DTM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AUTHOR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AUTHOR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Forum.TITLE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Forum.TITLE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cowell-GuestBook/Views/Article/Details.cshtml
@model Cowell_GuestBook.Models.ARTICLE

@{
    ViewBag.Title = "Details";
}
<div>
    <h4>@Html.DisplayFor(model => model.Forum.TITLE)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TITLE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TITLE)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AUTHOR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AUTHOR)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BODY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BODY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BUD_DTM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BUD_DTM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UPD_DTM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UPD_DTM)
        </dd>
    </dl>
</div>


@* 在文章內才可以回復 *@
<p>
    @Html.ActionLink("回覆文章", "Create", "Reply", new { articleID = Model.ID }, new { @class="btn btn-success"})
</p>

@*@Html.Action("index", "reply", new { articleID = Model.ID})*@
@* 方法三，給Partial View的MODEL直接在這邊取得，不走Controller *@
@Html.Partial("_ReplyList",Model.ARTICLEREPLY.OrderBy(x=>x.BUD_DTM).ToList())

Cowell-GuestBook/Views/Article/Edit.cshtml
@model Cowell_GuestBook.Models.ARTICLE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ARTICLE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.FORUM_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TITLE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TITLE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TITLE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AUTHOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AUTHOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AUTHOR, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BODY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.BODY,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BODY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cowell-GuestBook/Views/Article/Index.cshtml
@model IEnumerable<Cowell_GuestBook.Models.ARTICLE>

@{
    Cowell_GuestBook.Models.Forum ForumDetailModel = ViewData["ForumDetailModel"] as Cowell_GuestBook.Models.Forum;
}
@{
    if (ForumDetailModel != null) {
        @*方法1：透過Html.action完整跑一次生命週期，把明細Load進來，有點像是IFRAME的概念*@
        @*@Html.Action("details", "forum", new { id=Model.FirstOrDefault().FORUM_ID})*@

        @* 方法2：將資料做成部分頁面(Partial View)，直接在本次生命週期內使用，並給予該頁面所需要的Model *@
        @Html.Partial("_ForumDetail", ForumDetailModel)
        <p>
            @* 新建文章某討論區的文章，直接給予討論區參數，不讓使用者在新增文章頁面選取，同時，在所有文章列表，不允許新增文章 *@
            @Html.ActionLink("發帖子", "Create", new { ForumID = ForumDetailModel.ID }, new { @class="btn btn-success"})
        </p>
    }
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TITLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BUD_DTM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UPD_DTM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AUTHOR)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @{
        if (item.ARTICLEREPLY.Count() > 10) {
            <span class="label label-danger">爆</span>
        }
                }
                @Html.ActionLink(item.TITLE, "Details", new { id = item.ID })
                <span class="badge">@item.ARTICLEREPLY.Count()</span>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BUD_DTM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UPD_DTM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AUTHOR)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class="btn btn-sm btn-default"})
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-sm btn-default" })
            </td>
        </tr>
    }

</table>